[package]
name = "rtmpproxy"
version = "0.1.0"
authors = ["vizee <vizee@live.cn>"]
edition = "2018"

[dependencies]
lazy_static = "1.3"
tokio = "0.2.0-alpha"
tokio-threadpool = "0.2.0-alpha"
toml = "0.5"
url = "2.0"
